name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Create Fresh Android Scaffold
        run: |
          flutter create . --platforms=android --org=com.rehan.habit
          
      - name: Get Dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --debug
        
      - uses: actions/upload-artifact@v4
        with:
          name: LevelUp-App
          path: build/app/outputs/flutter-apk/app-debug.apk
